

INSERT INTO series (id, title, seasons_count, episodes_count)
VALUES ('d2b4a6e1-9f3c-482a-b751-2c9e8d4f0b1a', $$Off Campus$$, 1, 8);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('e1c5b7f2-a04d-593b-c862-3d0f9e5a1c2b', 'd2b4a6e1-9f3c-482a-b751-2c9e8d4f0b1a', 1, 1, 1, $$The Deal$$, $$Briar University hockey captain Garrett Graham, who has already been drafted by the Boston Bruins, is struggling in his philosophy class and needs a passing grade to continue playing. Hannah Wells, a music major and a top student in the same class, is working as a janitor in the locker room when she accidentally walks in on Garrett nude in the showers. Embarrassed and flustered, she runs off, amusing Garrett. After noticing Hannah's A grade on a class essay, he recruits her to tutor him. Aware of her crush on classmate Justin Kohl, Garrett proposes to Hannah that they pretend to be a couple so she can gain Justin's attention. After some initial reluctance on Hannah's part because of her distaste of hockey and some of Garrett's jock antics, the two agree on the deal.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('f2d6c803-b15e-6a4c-d973-4e1a0f6b2d3c', 'd2b4a6e1-9f3c-482a-b751-2c9e8d4f0b1a', 1, 2, 2, $$The Practice$$, $$Garrett and Hannah practice kissing and pretend to be a couple in public, wanting Jules, the sibling of Garrett's teammate John Logan, to post about the relationship on their social media gossip account. The two become closer after a party in which Hannah and Garrett open up to each other about their respective love of music and hockey. Garrett confides how his father Phil has prepared him for a career in hockey since he was a kid. Garrett and John's teammate Dean sees Allie, Hannah's best friend and roommate, at the party and they share a brief charged moment on the dance floor, but she turns him down. Jules publishes a photo of Hannah and Garrett to the account. The next day, as Hannah boards a bus headed to a Briar Hawks game, Justin approaches Hannah and sits beside her, witnessed by a Garrett, who's been developing feelings for Hannah.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('03e7d914-c26f-7b5d-ea84-5f2b107c3e4d', 'd2b4a6e1-9f3c-482a-b751-2c9e8d4f0b1a', 1, 3, 3, $$The Orgasm$$, $$Hannah grows closer to Justin and asks him to collaborate with her on a song for a pop songwriting competition. It is revealed that Hannah is uncomfortable in her own body after she was raped by a hockey player in high school. On karaoke night at Malone's Bar, Hannah gets drunk and sings "Cherry Pie" as Garrett starts to see her in a new light. He takes Hannah back to his place, but when she tries to seduce him, he stops her and tells her to sleep it off. Hannah gets a text message from Justin inviting her to come over to his place to work on songwriting, and she realizes she wants to be prepared for potential sex with Justin. When Garrett wakes up, Hannah asks him for a favor—if he could give her an orgasm, which she's only managed to give herself while alone.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('14f8ea25-d370-8c6e-fb95-603c218d4f5e', 'd2b4a6e1-9f3c-482a-b751-2c9e8d4f0b1a', 1, 4, 4, $$The Breakup$$, $$After Hannah opens up about her assault and intimacy struggles, Garrett agrees to help her as a friend. Allie breaks up with her boyfriend Sean, but he expects it won't last. That night, Hannah arrives to Garrett's place, and, after setting Hannah at ease with the song "Baby, Now That I've Found You" on his phone, they begin to have sex. However, Hannah tenses up and cannot go through with it, so Garrett proposes they instead separately bring themselves to orgasm in front of each other. After completing the task, Garrett comes to openly accept that he truly likes Hannah, and his teammates urge him to tell her at the Drunk Shakespeare event. Justin is also at the event and confesses his interest in Hannah to her. After reassuring him she isn't serious with Garrett, she happily tells Garrett their "deal" worked since he got the grade and she got the guy. Garrett leaves the event dejected that Hannah likes someone else and goes to the ice rink to practice alone. After a conversation with Justin in which Hannah realizes it's Garrett she loves, she goes to the rink and sings "Baby, Now That I've Found You" to him on the sound system.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('2509fb36-e481-9d7f-0ca6-714d329e506f', 'd2b4a6e1-9f3c-482a-b751-2c9e8d4f0b1a', 1, 5, 5, $$The Cold Turkey$$, $$Garrett and Hannah confess their mutual feelings for each other and become a real couple. For the Thanksgiving break, Phil asks Garrett to come home so he can introduce him to his new fiancée, Cindy. Though Garrett is reluctant to spend time with Phil, Hannah insists he go and accompanies him. John and Tucker, another member of the hockey team, stay on campus for Friendsgiving, which turns from a small gathering to a big one when other Hawks players bring their friends. Being at Phil's home dredges up memories for Garrett of the domestic abuse of his late mother by his father. He storms out with Hannah after realizing that Phil has also been abusing his fiancée Cindy. Garrett confides to Hannah about the abuse and his fears of becoming his father, and she reassures him he is not Phil. Meanwhile, Allie is revealed to be secretly hooking up with Dean since her breakup.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('361a0c47-f592-ae80-1db7-825e43af6170', 'd2b4a6e1-9f3c-482a-b751-2c9e8d4f0b1a', 1, 6, 6, $$The Breakaway$$, $$The details of Allie and Dean's relationship are shown, the two having grown closer after karaoke night at Malone's and regularly engaging in no-strings-attached sex after her breakup with Sean. Allie wants their hookups to remain casual and secret for fear of hurting Sean's feelings so soon after a breakup, but also cannot resist Dean's charms. Allie and Dean spend Thanksgiving together at his parents' place in New York City, unbeknownst to their friends. At a hockey fundraising event at Malone's, tensions between Garrett and John over Phil's involvement in their fundraiser come to a head. After Allie spends another night with Dean, Sean accidentally walks in on her alone. Realizing she is already with someone new, Sean walks away in disgust.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('472b1d58-06a3-bf91-2ec8-936f54b07281', 'd2b4a6e1-9f3c-482a-b751-2c9e8d4f0b1a', 1, 7, 7, $$The Faceoff$$, $$Joanna Maxwell, a Broadway actress and Beau's sister, visits campus and bonds with Allie over theater and acting. At a bar that night, Allie vents about her guy problems to Joanna. To prove that Allie can have successful casual relationships, Joanna goads her to approach a guy at the bar and they kiss. At the hockey game against St. Anthony's, Garrett struggles against rival Aaron Delaney. Aaron is revealed as Hannah's rapist, which is unknown to Garrett. Aaron sees Hannah kissing Garrett off the ice, and during the game, insults her to Garrett's face. An enraged Garrett loses his cool and beats Aaron up. As a result, Garrett is suspended for four games. Hannah confronts Garrett, saying she didn't need him to defend her in a violent manner. After a heated argument, the couple breaks up.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('583c2e69-17b4-c0a2-3fd9-047065c18392', 'd2b4a6e1-9f3c-482a-b751-2c9e8d4f0b1a', 1, 8, 8, $$The Line Change$$, $$Hannah drops out of the song competition. Garrett gives the captainship to John and decides to quit hockey, as he felt he was only doing it to please Phil. When Hannah sees Garrett skating at the rink alone, she reasons why he shouldn't quit. She changes her mind about the song contest and manages to sneak in a final spot at the showcase. Allie convinces Dean to bring Garrett and friends to the contest to watch Hannah. Hannah performs her song "The Girl That I Am", inspired by her past trauma. Afterwards, Garrett apologizes to Hannah and asks for another chance; the couple happily reconciles. Meanwhile, to create distance in her relationship with Dean, Allie suggests to him that they sleep with other people. Dean is not able to follow through, but Allie has sex with the man from the bar. While the team spends a night out at Malone's, John explains he recruited a new member to the Hawks after Garrett's suspension, who is revealed to be Allie's hookup, Hunter Davenport. At Malone's, Hunter immediately gets into a fight with Dean and the other guys, due to a past incident involving Dean's younger sister.$$);


-- Source: https://en.wikipedia.org/wiki/Off_Campus-- Content licensed under CC BY-SA 3.0.
-- Content licensed under CC BY-SA 3.0.
