INSERT INTO series (id, title, seasons_count, episodes_count)
VALUES ('c4b11f71-8a9d-4c3e-b2d9-123456789abc', $$Lupin$$, 2, 17);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('ef2e5494-8c69-44eb-aeb8-3b2ef0642c4e', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 1, 1, 1, $$Chapter 1$$, $$Assane Diop plans the theft of an expensive diamond necklace, once owned by Marie Antoinette, which his father Babakar had been accused of stealing from the wealthy Pellegrini family 25 years earlier. He enlists the help of a group of loan sharks, to whom he owes money. Under the alias "Paul Sernine", Assane attends an auction for the necklace, hosted by the Pellegrinis at the Louvre. He makes the winning bid, but the loan sharks, disguised as museum security guards, double-cross him and steal the necklace. However, their getaway goes awry and they are arrested, while Assane ends up in possession of the diamonds and walks free. Later that night, while investigating the case, a police detective named Youssef Guédira notices that it bears a striking resemblance to the stories of Arsène Lupin, and then realizes that "Paul Sernine" is an anagram of Lupin's name. The day after the heist, Assane gives his son, Raoul, a copy of Arsène Lupin, Gentleman Burglar, gifted to him by Babakar, who died in prison by an apparent suicide shortly after being convicted for the original necklace theft.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('0fa3cf96-5d2e-45a8-b6eb-7c1efbabf75e', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 1, 2, 2, $$Chapter 2$$, $$Assane's best friend, antiquarian Benjamin Férel, informs him that the queen's necklace was unlikely to ever have been deconstructed after being stolen as had been previously claimed by the Pellegrini family. Assane begins doubting that his father was responsible for the initial theft and confronts Juliette Pellegrini, who acknowledges that her family's story about the necklace's recovery was a lie concocted to drum up publicity, but affirms her belief in Babakar's guilt. Unsatisfied, Assane gets himself placed in jail so that he can speak to Étienne Comet, a man who worked at the prison library during his father's incarceration. A sickly Comet leads Assane to a copy of The Confessions of Arsène Lupin, with annotations from his father spelling out the phrase "I am innocent—framed by Anne Pellegrini". Assane escapes prison and finds Anne, who admits that she had instructed Babakar to sign a false confession at the urging of an Inspector Gabriel Dumont. Assane recognizes Dumont as the police officer who turned him over to social services following Babakar's death. Meanwhile, Guédira continues to investigate the Arsène Lupin connection, happening upon Babakar's case file.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('14cdf0fb-856c-4b8b-bc4e-8212b1bf525d', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 1, 3, 3, $$Chapter 3$$, $$After learning that Inspector Dumont was responsible for handling the case against his father, Assane kidnaps the now-Commissioner Dumont from one of Paris's town halls and tries to force him into confessing to having framed Babakar. 25 years earlier, a younger Dumont figures out that Hubert Pellegrini, who had recently had the necklace's insurance policy increased, masterminded its disappearance and set Babakar up to take the fall. When he realizes that Dumont is building a case against him for insurance fraud, Hubert mentions his powerful connections and threatens to have the police officer's wife harmed, which convinces Dumont to trick Anne into getting Babakar to sign the confession. In the present, Dumont maintains that he legitimately believed Babakar was guilty, although Assane manages to get him to admit to having accepted bribes from criminals in order to pad his salary. However, the interrogation grinds to a halt when an enraged Assane accidentally reveals his identity. The police, meanwhile, scramble to locate their commissioner, and Assane escapes just before they can catch him. Dumont is rescued but does not reveal any information about the identity of his kidnapper. Later, Guédira discovers Dumont's involvement with the original investigation and connects it to the necklace's theft and the abduction.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('52dca87f-6bb3-4e46-9a5a-b53ee8b75bcc', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 1, 4, 4, $$Chapter 4$$, $$Assane finds Dumont again and coerces him into providing more information about Hubert Pellegrini. Dumont gives him the name of Fabienne Bériot, a former investigative journalist who was sued for defamation by Hubert after she publicly denounced his corruption in a book titled Dirty Money: The Pellegrini System. Fabienne agrees to team up with Assane and helps him acquire a tape connecting the entrepreneur's arms dealing to a deadly terrorist attack on a French embassy in Kuala Lumpur. Under the alias "Salvator813", Assane posts an image from the tape on Twitter, threatening to release the full video. Hubert publicly denies the allegations, and his henchman Léonard Koné begins stalking Fabienne. Meanwhile, Guédira is removed from the necklace investigation by Dumont, who realizes the detective is closing in on the truth about his involvement in the original case. A heavily disguised Assane's plan to expose Hubert on the talk show The Other Edition fails when Hubert, who is friends with the show's host, manages to have the footage altered. Juliette, now convinced of her father's innocence, reveals to him that Assane is behind the accusations, as well as the Louvre heist. Léonard attacks Fabienne in her home and demands to know where Assane lives, but Fabienne refuses to give him the information. To his horror, Assane returns to discover her body hanging from the ceiling.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('25ead1f6-1a99-4287-a9ba-f6c262de7289', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 1, 5, 5, $$Chapter 5$$, $$Following Fabienne's death, Assane gives her dog, J'accuse, to Benjamin. On Raoul's birthday, Assane surprises him with a top hat and cape and takes him and Claire on a train trip to a Lupin-themed festival in Étretat. Léonard, who has begun pursuing Assane, follows the family onto the train, with orders from Hubert to get rid of Assane but to leave Claire and Raoul alone. Assane spots Léonard and fights him in a storage closet at the back of the train, managing to lock him inside. As the train pulls into its destination, however, Léonard escapes the closet and sits beside Raoul. In an attempt to manage the situation, Assane instructs his family to disembark ahead of him and manipulates the local police into arresting Léonard by suggesting that he is Paul Sernine. After Assane catches up, the family makes it to the festival without incident. While Raoul explores the beach by himself, a concerned Claire questions Assane about Léonard but grows distressed when he avoids telling her the truth. Assane promises that he will stop hiding things from her in the future and asks her for one more chance to prove himself. Léonard, meanwhile, is released from police custody and kidnaps Raoul. Claire becomes worried upon noticing that she cannot see Raoul on the beach, and she and Assane begin a fruitless search for him. Guédira appears and calls out to Assane, addressing him quizzically as "Lupin".$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('2e695cae-b3a5-4968-9973-9e1d92e6139e', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 1, 6, 6, $$Chapter 6$$, $$Guédira informs Assane and Claire that he saw Raoul struggling with Léonard in a parking lot, and that the two drove away. Claire is horrified and blames Assane for the kidnapping; Assane unsuccessfully tries to reassure her that he will bring Raoul back to her safely. Guédira, aware that Assane is the man he is searching for, offers to help him track Léonard down, and the two steal a car and give chase. Remaining in Étretat, Claire contacts the local police but is upset by the lack of urgency in their response and returns to Paris, intending to seek help from Benjamin. Meanwhile, Assane and Guédira locate Léonard in the town of Bourneville and tail him to an abandoned mansion, where Léonard, who has Raoul bound and gagged, is lying in wait. Guédira quietly contacts Sofia Belkacem and asks her for assistance, but Assane ties him up inside the car after revealing that he knows that Guédira is a police officer. Assane enters the house, fights Léonard, and throws him out of a window. However, Léonard, who has locked Raoul in the boot of his car, manages to stand up, douses the car in gasoline, and sets it alight. When he sees the burning vehicle and realizes what has happened, Assane is devastated and breaks down. A moment later, Belkacem appears and arrests him.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('fbc52cb5-b65f-4dca-94b4-3cc02b43da8d', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 1, 7, 7, $$Chapter 7$$, $$Prior to Belkacem's arrival, Guédira escapes his bindings and successfully rescues Raoul from Léonard's car without Assane's knowledge. Afterwards, he is informed that Dumont wants Raoul taken to the Park Hyatt hotel in central Paris, where Hubert and Juliette are hosting an event in honor of their foundation. Although confused, Guédira complies with the order. Hubert and Dumont hold Raoul hostage at the hotel, expecting Assane to walk into their trap. Assane, meanwhile, is extremely relieved when Belkacem tells him that nothing but a soda can was found in the boot of the car. He escapes police custody, steals another car, and drives to Paris, where he uses voice-altering technology to make himself sound like Hubert in order to successfully rescue Raoul from his captors. Unbeknownst to Assane, Claire has uncovered the truth of his activities after happening upon an image of his disguised appearance on The Other Edition. She confirms her fears with Benjamin and, desperate with worry for her son's safety, attempts to negotiate his release with Hubert directly, but Hubert forces her to betray Assane in exchange. When Assane brings Raoul back home, a number of Hubert's associates, led by Pascal Oblet, await him there. However, after Claire begs Pascal for a moment alone with Raoul, she manages to tell Assane to run away.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('99b860ff-6ffd-4cd8-ac80-2b39c5314c15', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 1, 8, 8, $$Chapter 8$$, $$Assane escapes from Pascal and his men and hides in the roof above Claire's apartment, where, to his dismay, he hears Claire tearfully telling Raoul that Assane is dangerous, and that she doesn't want him to come near them again. Having once again failed to ensnare Assane, Hubert makes plans for an upcoming charity concert for Juliette's foundation with a young stockbroker named Philippe Courbet, revealing that he intends to send 85% of the donations brought in during the event to a personal offshore bank account in the Cayman Islands. Meanwhile, Assane and Benjamin come up with an elaborate plan to weaken Hubert that involves Assane seducing Juliette by taking her on a joyride around Paris and pretending to steal a priceless Pissaro painting for her. The plan goes without a hitch, as Assane manipulates Juliette into talking to her mother about Hubert's crimes during the 1990s. When Juliette visits her, Anne admits that the necklace theft was an insurance scam, and that Hubert had hired Babakar with the intention of framing him for it. Juliette is shocked and urges Anne to denounce Hubert to the police. After learning the truth from Anne, Guédira and Captain Laugier arrest Hubert while he is meeting with Courbet.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('194ebf81-4548-46b7-83bf-eaa2cfcdba3e', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 1, 9, 9, $$Chapter 9$$, $$Laugier and Belkacem interrogate Hubert, who is uncooperative but does reveal Assane's real name. The police are ultimately forced to let Hubert go after he calls in a favor from the minister of the interior. Pascal discovers that Benjamin is Assane's accomplice and informs Hubert, who instructs Léonard to tail Benjamin in order to find out where Assane lives. Hubert also secretly arranges for Pascal to murder Léonard in Assane's apartment and to frame Assane for the crime. Their scheme is a success, and when Assane discovers what has happened and realizes that the police are on their way, he goes on the run and tells Benjamin to do the same. That night, Assane's identity is publicly revealed, and he immediately becomes the most notorious criminal in France. Over the next few days, Assane and Benjamin hide out, managing to evade capture using a secret bunker that connects to the Catacombs of Paris. Meanwhile, after finding a coded message from Assane, Guédira recovers a USB drive among the evidence taken from the apartment that contains footage of Dumont's interrogation, in which he admits to his having accepted illegal bribes, as well as more papers that link him to Babakar's case.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('a6be6b2c-9dbb-4e88-96ea-d7ba9f2b74c8', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 1, 10, 10, $$Chapter 10$$, $$Belkacem receives evidence from the police laboratory suggesting that Assane was not Léonard's murderer. Guédira informs her and Laugier about Dumont's corruption, and the three resolve to arrest him at the Pellegrinis' concert at the Théâtre du Châtelet that evening. Assane is smuggled into the theater with assistance from a disguised Benjamin and Philippe Courbet, actually an accomplice of Assane and Benjamin whom they had found attempting to steal Arsène Lupin books. When the music starts, Assane sneaks into Hubert's private box, holding him at knifepoint and forcing him to confess to having framed Babakar and orchestrated his murder, as well as the murders of Fabienne and Léonard and the kidnapping of Raoul. Assane is chased extensively through the theater by Hubert's men but manages to get onstage, where he publicly accuses Hubert of all of his crimes, including stealing from the foundation. He succeeds in evading the police by disguising himself as a firefighter, and sends Guédira a recording of Hubert's confession. While Guédira, Laugier, and Belkacem take Hubert and Dumont into custody, Assane steals a speedboat and arranges a reconciliatory meeting with Claire and Raoul on a nearby bridge. He apologizes for the pain his actions have caused them and tells them that he needs to stay away for their safety. As the police approach, he runs off into the night.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('ef8a4f43-e691-44b6-baf0-ae1caa44abcb', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 2, 1, 11, $$Chapter 1$$, $$One year after Assane's showdown with Hubert Pellegrini, he lives incognito in Marseille. Assane remains the most wanted man in France and has unintentionally become a folk hero. Claire and Raoul, meanwhile, are tormented by constant media harassment. Assane is furious at their treatment and decides to return to Paris, initially approaching Claire with a plan to spirit her and Raoul out of the country, but Claire is upset with Assane and rebuffs his offer, suggesting that the only way he could truly repay them would be to turn himself in. Undeterred, Assane plots to fund their escape by stealing an expensive black pearl from a luxury boutique located at the Place Vendôme, sending a letter to the shop's owner as well as the staff of the newspaper The Objector, explicitly stating his intentions. A squad led by Belkacem is summoned to the scene, where a large crowd of Assane's supporters is eagerly awaiting the burglary. Although he has not been assigned to the case, Guédira decides to tag along and mingles with the fans. Helped by Benjamin and another childhood friend, Bruno, both disguised as BRI officers, Assane's heist is successful. He escapes across the high roofs surrounding the square but fails to get a foothold on one of his attempts to jump to an adjacent building, and plummets to the streets below.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('7c689afd-40a0-4452-86f6-34fc896f9779', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 2, 2, 12, $$Chapter 2$$, $$Assane survives his fall, having planned to fake his death using an airbag and a vial of his own blood. His seemingly lifeless body is spirited off in an ambulance by Benjamin and Philippe Courbet before the police can arrive on the scene. Dressed in lab coats, Philippe and Benjamin use a broken stethoscope to successfully manipulate a doctor at the morgue into confirming the death, and the news of Assane's demise breaks shortly after. A funeral is held for him at Père-Lachaise Cemetery, where Guédira, skeptical of the reality of Assane's death, demands that the casket be opened, to the horror of Claire and Raoul. After the event has finished, Assane escapes the casket through a tunnel underneath the cemetery and reunites with Benjamin, who has managed to find a dealer who can get twenty million euros for the pearl. However, Assane's plans are put on hold when he receives a phone call from a woman claiming to be his mother, Mariama, to whom he had last spoken in 1998, when she was serving a prison sentence in Senegal. She pleads with Assane for help, telling him that she has been kidnapped and that her captors are requesting the black pearl as ransom.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('93d398fa-4dab-475b-9e06-a8a32bf8c324', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 2, 3, 13, $$Chapter 3$$, $$Frustrated that his ideas about Assane's connections to Arsène Lupin are still not being taken seriously by his colleagues, Guédira makes a deal with Objector journalist Fleur Bélanger to provide her with his evidence. The resulting story ultimately winds up rekindling public interest in Arsène Lupin. Like Guédira, Raoul is refusing to accept Assane's death, leading Claire to grow worried about his mental state. She gives her phone number to Raoul's new basketball coach, Alex, and asks him to let her know if her son is having any difficulties. Mariama's kidnappers order Assane to steal Chez Tortoni, a painting by Édouard Manet, currently in the illegal possession of a Nanterre-based gang leader named Cisco. In disguise, Assane ingratiates himself with Cisco's gang, managing to gain a position as a getaway driver in a robbery that they are planning. With some help from gadgets designed by Benjamin, Assane double-crosses the gang, leaving them to be arrested by the police, and makes off with the painting, which he gives to Ferdinand, one of the kidnappers, at an arranged rendez-vous point. Having placed a tracking device made by Benjamin onto the painting, Assane impulsively decides to follow Ferdinand to try and locate Mariama.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('32ae3272-b569-47e4-94d7-607568083e2c', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 2, 4, 14, $$Chapter 4$$, $$While at work, Claire is informed that the doctor who examined Assane's body is not in the hospital's database. Beginning to have her own doubts about what happened to Assane, she finds Raoul's written attempts to prove that his father is alive, in which he has highlighted the name of the Arsène Lupin story Edith Swan-Neck. After a semi-incognito trip to the library, Claire acquires the book and, while reading it, stumbles upon the phrase "with Lupin, there's no such thing as death". Meanwhile, Assane is forced by the kidnappers to plan the theft of a bracelet belonging to Tara Xang, wife of real estate magnate Max Moller, both of whom will be appearing at a gala at the Château de Thoiry. In preparation, Assane shows Benjamin how to escape through a hedge maze on the grounds of the château. Assane and Benjamin appear at the gala, posing as footmen. Unbeknownst to Benjamin, the actual price that Mariama's kidnappers had demanded was his own imprisonment. When Assane slips the bracelet from Xang's wrist, he drops it on the ground. As Benjamin leaps to pick it up, he is immediately spotted by Moller, who orders his capture. A panic-stricken Benjamin dashes out of the château into the maze but is horrified to find that a large hedge is blocking the path that had been specified for him. At that moment, Guédira and Belkacem, who had previously been called in by Assane, arrive and arrest him.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('1e417670-f021-4663-9a34-f4f0ca0dda78', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 2, 5, 15, $$Chapter 5$$, $$Still suspicious that Assane is alive, Guédira interrogates Benjamin in an attempt to get him to reveal Assane's location, but in spite of Assane's betrayal, Benjamin staunchly refuses to give him up. That afternoon, Guédira is shocked when he discovers Assane sitting in his office. Assane promises that he will allow himself to be arrested if Guédira assists him. Although apprehensive, Guédira accepts the offer. Assane disguises Guédira as a collector of stolen art and instructs him to meet with Manon, another of the kidnappers, and Ferdinand, in order to buy the Manet painting from them. Assane calls Belkacem and tips her off about the trade. As the deal is being done, she arrives and arrests Manon, while Ferdinand manages to escape. Assane tails Ferdinand and discovers that he is an accomplice of Jean-Luc Keller, a man whose boxing club Assane had joined as a teenager. Keller had forced Assane and Bruno to take part in a jewellery theft, but he had been the only one arrested for the crime and has carried a vendetta against Assane ever since. Under the guise of granting him an interview, Claire meets with Objector journalist Arnold de Garmeaux, who was present at the morgue when Assane's body was inspected, and asks him to describe the attending doctor to a sketch artist. She is startled when the sketch turns out to be a portrait of Benjamin. Claire visits Benjamin in prison and deceives him into thinking that Assane had confessed everything to her; Benjamin responds by asking what Assane's current plans are. Having received confirmation that Assane is alive, Claire begins to weep with joy.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('e6239c18-65be-44b1-a6a1-ec8134c5be50', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 2, 6, 16, $$Chapter 6$$, $$In retaliation for Manon's arrest, Keller orders Ferdinand to kill Claire and Raoul. Claire notices Ferdinand stalking her and manages to evade him, but her worries about future attacks lead her to invite Alex, Raoul's basketball coach, to stay for dinner. Claire has become smitten with Alex due to his softly-spoken bravery and his protectiveness of Raoul. After Raoul has gone to bed, Claire attempts to kiss Alex, but to her dismay, he turns down her advances and leaves after showing her how to set up her alarm system. The following morning, Claire finds a ketchup bottle standing upside-down in the refrigerator, a quirk of Assane's that she had first noticed when they were teenagers, and realizes that Alex is in fact Assane in an elaborate disguise. Meanwhile, Mariama manages to escape captivity and places an advertisement in The Objector, asking Assane to meet her at a metro station. Assane and his mother enjoy a happy reunion. Keller is outraged by the loss of Mariama and Ferdinand's inability to catch Claire, so he throws Ferdinand from a balcony and decides to take care of Assane's family himself. That night, Claire happily lies in bed, with her romantic feelings for Assane fully rekindled, but grows terrified when she hears Keller begin to break down the door of her apartment.$$);

INSERT INTO episode (id, series_id, season, episode_number, episode_index, title, summary)
VALUES ('9a685afd-40a0-4152-86f6-34fc896f9779', 'c4b11f71-8a9d-4c3e-b2d9-123456789abc', 2, 7, 17, $$Chapter 7$$, $$Claire hides in a closet with Raoul and throws Keller off the trail by making a call to her home phone, in which she implies that neither she nor Raoul are there and that a police officer will be visiting. Afterwards, she calls Assane and begs him to pick her and Raoul up. Assane brings Claire and Raoul to his hideout, where they meet Mariama; he promises that he will get all of them out of Paris. Assane and Mariama infiltrate the offices of the minister for the interior and steal his phone. After threatening to send the contents of the phone to the press, Assane orders the minister to let Manon out of prison. Assane finds Manon and asks her to help him catch Keller. Although initially reluctant, she has a change of heart when Assane explains Keller's manipulative behaviour. Manon calls Keller and tells him that she has found a buyer for the black pearl at the Arc de Triomphe. When Keller arrives for the rendez-vous, he finds only Assane, who has called the police. Keller realizes that he has been set up and tries to run, but he is captured. Making good on his earlier promise, Assane allows Guédira to arrest him, on the condition that Benjamin be set free. Claire arrives at the train station the following morning with Raoul and Mariama in tow, eagerly awaiting Assane's arrival. However, it is Benjamin who turns up, carrying a letter from Assane in which he explains his actions and assures a heartbroken Claire how much he loves her. Assane settles into life in jail but is shocked when he receives an envelope from a neighbouring inmate containing a photograph of Assane as a teenager holding an Arsène Lupin book, Cagliostro's Revenge. The fellow prisoner turns out to be Hubert Pellegrini.$$);
